---
- name: Pavlov Server Setup
  hosts: server1
  become: yes
  tasks:
    - name: Update apt cache and install pavlov dependencies
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - gdb
        - curl
        - lib32gcc-s1
        - nano
        - libc++-dev
        - unzip

    - name: Create steam user
      ansible.builtin.user:
        name: steam
        password: "{{ 'gonnaglorp1024' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

    - name: Add user to sudo
      user:
        name: steam
        groups: sudo
        append: yes

    - name: Create Steam dir
      become_user: steam
      ansible.builtin.file:
        path: ~/Steam
        state: directory
        owner: steam
        mode: 0755

    - name: Download SteamCMD installer to home directory
      become_user: steam
      ansible.builtin.get_url:
        url: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
        dest: /home/steam/steamcmd_linux.tar.gz
        mode: '0644'
        owner: "steam"
        group: "steam"

    - name: Untar downloaded steamcmd
      become_user: steam
      ansible.builtin.unarchive:
        src: ~/Steam/steamcmd_linux.tar.gz
        dest: ~/Steam
        remote_src: yes
        mode: '0755'        

    - name: Install Pavlov server from SteamCMD
      become_user: steam
      ansible.builtin.command:
        cmd: ~/Steam/steamcmd.sh +force_install_dir /home/steam/pavlovserver +login anonymous +app_update 622970 +exit
        creates: ~/pavlovserver

    - name: Fix Libc
      ansible.builtin.command:
        cmd: rm /usr/lib/x86_64-linux-gnu/libc++.so 
        removes: /usr/lib/x86_64-linux-gnu/libc++.so
    
    - name: Fix libc
      ansible.builtin.command:
        cmd: ln -s /usr/lib/x86_64-linux-gnu/libc++.so.1 /usr/lib/x86_64-linux-gnu/libc++.so
        creates: /usr/lib/x86_64-linux-gnu/libc++.so

    - name: Set execution permissions on PavlovServer script
      become_user: steam
      ansible.builtin.file:
        mode: '0755'
        path: ~/pavlovserver/PavlovServer.sh

    - name: Create pavlov dirs
      become_user: steam
      ansible.builtin.file:
        path: /home/steam/pavlovserver/Pavlov/Saved/Logs
